### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by Dallas62** [redgeoff/delta-pouch#104]
I just try cleanup method on a test database, and it result on a deletion of all updates made.

Exemple:

First doc:
```
{
_id: 123,
prop1: true,
prop2: 'value'
}
```
Update 1:  prop1 true => false
Result a new document:
```
{
_id: 123 + timestamp,
$id: 123,
prop1: fasle
}
```
.all() result: 
```
{
$id: 123,
prop1: false,
prop2: 'value'
}
```
Execute .cleanup(),
.all() result:
```
{
$id: 123,
prop1: true,
prop2: 'value'
}
```
And document "Update 1" (123+timestamp) as disappear from database.

**Comment by dawnmist** [comment]
It does the same thing on the [websites live demo](http://redgeoff.github.io/delta-pouch/examples/websites/?iris) (you can see it immediately in the devtools for application/idb, though you need to reload the page to see the text get updated to reflect that the edits were lost).

Since that example is one of the two live demos for the package, it should be pretty easy to use as a test case.
